completed es6-classes exercise.
RossBrewster/c-0823-code-solutions pull request #69
Opened 2023-09-26 23:18 UTC by RossBrewster

![Screenshot 2023-09-26 at 4 15 21 PM](https://github.com/RossBrewster/c-0823-code-solutions/assets/124334539/309065d5-f825-4359-97d6-0a825ce2f909)
![Screenshot 2023-09-26 at 4 15 07 PM](https://github.com/RossBrewster/c-0823-code-solutions/assets/124334539/b4afbaf0-0715-41ae-918c-058554a9127b)
![Screenshot 2023-09-26 at 4 15 14 PM](https://github.com/RossBrewster/c-0823-code-solutions/assets/124334539/747b0b25-d8fd-4696-80a4-68398da8ff0d)

2023-09-26 23:22 UTC, shawnkost requested changes
Couple changes here Ross!

2023-09-26 23:22 UTC, shawnkost commented on es6-classes/circle.js
> +    this.perimeter = 2 * Math.PI * radius;
You shouldn't be creating these properties manually. You should be utilizing `super` to generate these properties for you

2023-09-26 23:22 UTC, shawnkost commented on es6-classes/square.js
> +    this.perimeter = width * 4;
You shouldn't be creating these properties manually. You should be utilizing `super` to generate these properties for you

2023-09-26 23:37 UTC, RossBrewster commented
Is this what you mean?

2023-09-26 23:40 UTC, shawnkost requested changes
Not quite Ross! Left a comment below but it applies to both files

2023-09-26 23:40 UTC, shawnkost commented on es6-classes/circle.js
> +    super.perimeter = 2 * Math.PI * radius;
Not quite! You're not setting the `area`  & `perimeter` properties directly on `super`. You're supposed to call `super` and pass in the data that you want `area` & `perimeter` to be. When you do `super()` you are calling your `Shape` constructor function, which will generate the `area` & `perimeter` properties for you. So you just need to pass data into that function, to set it's values

2023-09-26 23:48 UTC, RossBrewster commented
Third time's the charm.

2023-10-09 16:24 UTC, shawnkost approved these changes
👍🏻

2023-10-09 18:44 UTC, merged